### ISSUE TITLE
the problem of  "\ufeff" with a num

### ISSUE THREAD

**Issue by guantou** [wargarblgarbl/libgosubs#6]
https://github.com/wargarblgarbl/libgosubs/blob/7f03fb80e6de518d1533b4db0ed76b93d6a11a77/srt/readsrt.go#L49

https://github.com/wargarblgarbl/libgosubs/blob/7f03fb80e6de518d1533b4db0ed76b93d6a11a77/srt/readsrt.go#L63

if the file is code with utf8+bom, this package parse srt fail :

the srt file like this:
```
1  // here ! it is \ufeff and 1
00:00:01,430 --> 00:00:03,230
前情提要

2
00:00:01,430 --> 00:00:03,230
{\pos(190.2,244.8)}西部世界
```

use  the function ParseSrt() to parse the file , go program throw error
```
strconv.Atoi: parsing "\ufeff1": invalid syntax
```

**Comment by wargarblgarbl** [comment]
@guantou Latest push to master should fix this problem.
