### ISSUE TITLE
archive repo

### ISSUE THREAD

**Issue by 3052** [wargarblgarbl/libgosubs#9]
no commits in 6 years

**Comment by wargarblgarbl** [comment]
No. 

Edit: Just for my own edification.  

1. Code still builds fine under the latest go. 
2. Code as it stands is feature complete, but there may be yet-undiscovered bugs
3. Code refactoring is still an option, but not necessary. 

Conclusion: repository will remain open indefinitely for the author to continue working on it as he pleases. 

The modern cliche of "no commits ergo dead" is dumb and unwelcome.
